sudo: required
services:
  - docker

before_install:
  - docker build -t wasay6788/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run wasay6788/react-test npm test -- --coverage

after_success:
  - docker build -t wasay6788/multi-client ./client
  - docker build -t wasay6788/multi-nginx ./nginx
  - docker build -t wasay6788/multi-server ./server
  - docker build -t wasay6788/multi-worker ./worker

  ## env on travis project
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wasay6788/multi-client
  - docker push wasay6788/multi-nginx
  - docker push wasay6788/multi-server
  - docker push wasay6788/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY